//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecipeRolodex.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Recipe()
        {
            this.IngredientSteps = new HashSet<IngredientStep>();
            this.InstructionSteps = new HashSet<InstructionStep>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.TimeSpan PrepTime { get; set; }
        public System.TimeSpan CookTime { get; set; }
        public long MealCategoryID { get; set; }
        public string UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IngredientStep> IngredientSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InstructionStep> InstructionSteps { get; set; }
        public virtual MealCategory MealCategory { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
